### ISSUE TITLE
Add post-build script for the action.yml file

### ISSUE THREAD

**Issue by BioPhoton** [push-based/user-flow-gh-action#58]
# Problem 
At the moment the repository contains 3 `action.yml` files. 
- `./packages/user-flow-gh-action/src/action.yml`
 - `./dist/packages/user-flow-gh-action/src/action.yml`
 - `./action.yml`

So we have a manual step managing the main `action.yml`.

# Solution

As GH actions need to have the `action.yml` located in the repository root to work we have to add some custom logic to move the file from `./dist/packages/user-flow-gh-action/src/action.yml` to `./action.yml` and update the main path.
We also need to delete/move the `./dist/packages/user-flow-gh-action/src/action.yml` file.

So in the end there should be only 2 files named `./action.yml`. 
One that is the source file and one that is generated by the build in dist. This needs to move into root.

This change and the as well as the effort to make it work initially was done by @LayZeeDK. 
Thanks again at this point! ♥♥♥

**TODO:**
- [x] Add a file under `./tools/scripts` named `post-build-user-flow-gh-action.ts`
  - [x] Move `./dist/packages/user-flow-gh-action/src/action.yml` to `./action.yml`
  - [x] Adopt the `runs.main` property to the new path
- [x] Execute  `./tools/scripts/post-build-user-flow-gh-action.ts` after the `build` target of the `user-flow-gh-action`
- [x] Adopt the `ci.yml` workflow to add the newly added  `./action.yml` to the git history, commit and push it to the existing PR
