### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ChristopherPHolder** [push-based/user-flow-gh-action#9]
# Motivation

Every PR could potentially include a performance regression.
Therefore need a way to continuously measure the performance to inform developers about performance slowdown before the PR gets merged.

To accomplish this, we need a way to compare the measures of the current branch against the measure of the target branch. 

# Suggested solution

The solution will use `@push-based/user-flow` and wrap it in a GitHub action to interact with the PR.

There are different building blocks necessary to implement this feature:

**Legend:**
- ‼ - important for second contact https://github.com/push-based/user-flow/issues/45

**Building blocks**
- [report visualization](https://github.com/push-based/user-flow-gh-action/issues/9#issuecomment-1302272811) - a comment in the PR that a human can interpret e.g. MD table
- report comparison - logic that compares 2 measures and calculates the diff
  - [report comparison visualization](https://github.com/push-based/user-flow-gh-action/issues/9#issuecomment-1302315256) - a comment in the PR that a human can interpret e.g. MD table
- assertions - a way to let the gh action fail if the budget is exceeded 
  - performance budgets - A definition of a data structure that can be reflected as `JSON`

# Implementation

We have to split into 2 responsibilities/packages here:
- 💻 the CLI - `@push-based/user-flow` 
- ⚙ the CI Action - CI related code e.g. GitHub Action `@push-based/user-flow-gh-action`

To implement the building blocks we need to solve a couple of core problems:

- [x] ‼⚙ interact with a PR and maintain a comment - #80
  - [x] ‼⚙ decide on comment update and re-run logic  - #10
- [x] 💻 pure function to compare 2 (reduced?) reports
https://github.com/push-based/user-flow/issues/94
  - [ ] 💻 handling git checkout and target branch 
- [ ] 💻 performance budgets - Lighthouse budgets and/or custom version
  - [x]  💻 LH budgets technically is a separate LH audit => https://github.com/GoogleChrome/lighthouse/issues/6053
  - [ ] 💻 custom budgets will be applicable to all measurement modes (navigation, timespan, snapshot), LH budgets just to navigation
- [x] ‼💻 visualization of report -> --format md
  - [x] 💻 have the different measures on the vertical axis is the way to go as there can be a lot. 
- [ ] 💻 visualization of comparison
  - [x] 💻show the diff in the same unit as the measure e.g. 7 / 2 ⬇
  - [ ] 💻 Implement assert command
  - [ ] ⚙ aggregate reports into one text piece
- [x] ‼💻Setup GH action automatically - https://github.com/push-based/user-flow/issues/198

# Documentation

- It should link to the user-flow repo https://github.com/push-based/user-flow
- How to set it up?
- Use Cases
  - Report visualization
  - Report comparison visualization 
  - Setup assertions

# References

- [GH comments](https://github.com/marketplace/actions/sticky-pull-request-comment)
- Comparison visualizations:
  - <img width="200px" src="https://user-images.githubusercontent.com/2301202/70814650-85c58800-1d91-11ea-925e-af9d03f1b20d.png"> 
  - <img width="200px" src="https://raw.githubusercontent.com/andresz1/size-limit-action/master/assets/pr.png" >
  - <img width="200px" src="https://raw.githubusercontent.com/mdsadiq/lighthouse-compare/main/images/pr_comment.png" >

**Comment by BioPhoton** [comment]
# [UserFlowName] - Report Visualization

__Date/Time:  2022-11-03 15:06__

<details>
  <summary>Report Summary</summary>

| Step Name               | Gather Mode | Performance | Accessibility | Best Practices | Seo | Pwa |
| :---------------------- | :---------: | :---------: | :-----------: | :------------: | :-: | :-: |
| Navigate to coffee cart | navigation  |     90      |      97       |      100       | 83  | 30  |
| Select coffee           |  timespan   |    11/11    |       -       |      7/7       |  -  |  -  |
| Coffee selected         |  snapshot   |    Ø 3/3    |     15/16     |      5/5       | 7/9 |  -  |
| Checkout order          |  timespan   |    13/13    |       -       |      7/7       |  -  |  -  |
| Order checked out       |  snapshot   |    Ø 3/3    |     17/18     |      5/5       | 7/9 |  -  |
| Submit order            |  timespan   |    13/13    |       -       |      7/7       |  -  |  -  |
| Order submitted         |  snapshot   |    Ø 3/3    |     15/16     |      5/5       | 7/9 |  -  |
</details>

<details>
  <summary>Settings</summary>
 table here

</details>

**Comment by BioPhoton** [comment]
# [UserFlowName] - Report Comparison Visualization

before 80 now 90

__Date/Time:  2022-11-03 15:06__

<details>
  <summary>Comparison Summary</summary>

| Step Name               | Gather Mode | Performance | Accessibility | Best Practices | Seo | Pwa |
| :---------------------- | :---------: | :---------: | :-----------: | :------------: | :-: | :-: |
| Navigate to coffee cart | navigation  |     90 (10⏫)      |      97       |      100      | 83  | 30  |
| Select coffee           |  timespan   |    10/11 (1⏬)  |       -       |      7/7       |  -  |  -  |
| Coffee selected         |  snapshot   |    Ø 3/3    |     16/16 (1⏫)    |      5/5       | 7/9 |  -  |
| Checkout order          |  timespan   |    13/13    |       -       |      5/7 (2⏬)       |  -  |  -  |
| Order checked out       |  snapshot   |    Ø 3/3    |     17/18     |      5/5       | 7/9 |  -  |
| Submit order            |  timespan   |    13/13    |       -       |       6/7 (1⏬)       |  -  |  -  |
| Order submitted         |  snapshot   |    Ø 3/3    |     15/16     |      5/5       | 7/9 |  -  |
</details>

<details>
  <summary>Settings</summary>
 table here

</details>

**Comment by BioPhoton** [comment]
# [UserFlowName] - Report Comparison Visualization v2

before 80 now 90

__Date/Time:  2022-11-03 15:06__

<details>
  <summary>Comparison Summary</summary>

| Step Name               | Gather Mode | Performance | Accessibility | Best Practices | Seo | Pwa |
| :---------------------- | :---------: | :---------: | :-----------: | :------------: | :-: | :-: |
| Navigate to coffee cart | navigation  |     90 (10💚)      |      97       |      100      | 83  | 30  |
| Select coffee           |  timespan   |    10/11 (1🔻)  |       -       |      7/7       |  -  |  -  |
| Coffee selected         |  snapshot   |    Ø 3/3    |     16/16 (1💚)    |      5/5       | 7/9 |  -  |
| Checkout order          |  timespan   |    13/13    |       -       |      5/7 (2🔻)       |  -  |  -  |
| Order checked out       |  snapshot   |    Ø 3/3    |     17/18     |      5/5       | 7/9 |  -  |
| Submit order            |  timespan   |    13/13    |       -       |       6/7 (1🔻)       |  -  |  -  |
| Order submitted         |  snapshot   |    Ø 3/3    |     15/16     |      5/5       | 7/9 |  -  |
</details>

<details>
  <summary>Settings</summary>
 table here

</details>

**Comment by BioPhoton** [comment]
For the following tasks we need to do more research:
- handling git checkout and target branch => maybe better in the CLI?

**Comment by BioPhoton** [comment]
Related to:
- #10 
- https://github.com/push-based/user-flow/issues/15
-

**Comment by ChristopherPHolder** [comment]
Related to: push-based/user-flow#94
